# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patch_app', '0002_testpatchnotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatchNotes',
        ),
        migrations.DeleteModel(
            name='TestPatchNotes',
        ),
    ]
